import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import { Card, Container, FormControl, Row, Col } from "react-bootstrap";
import { useQuery } from "react-query";

const getPokemon = async (key, query) => {
  const { data } = await axios.get(`/api/search?q=${escape(query)}`);
  console.log(data);
  return data.map((pokemon) => ({
    ...pokemon,
    image: `/pokemon/${pokemon.name.english
      .toLowerCase()
      .replace(" ", "-")}.jpg`,
  }));
};

export default function Home() {
  const [query, setQuery] = useState("");
  const { data } = useQuery("query", getPokemon);
  console.log(data);
  return (
    <>
      <Head>
        <title>Pokemon!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <FormControl
          placeholder="Search"
          aria-label="Search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        {data && (
          <Row>
            {data.map(({ id, name, type }) => (
              <Col xs={4} key={id} style={{ padding: 5 }}>
                <Card>
                  <Card.Body>
                    <Card.Title>{name.english}</Card.Title>
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </Row>
        )}
      </Container>
    </>
  );
}
